-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM_controller\pwm_controller_pwm_controller_pcore_addr_decoder.vhd
-- Created: 2014-10-15 17:50:19
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pwm_controller_pwm_controller_pcore_addr_decoder
-- Source Path: pwm_controller_pwm_controller_pcore/pwm_controller_pwm_controller_pcore_axi_lite/pwm_controller_pwm_controller_pcore_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pwm_controller_pwm_controller_pcore_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_enable                      :   OUT   std_logic;  -- ufix1
        write_duty                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        write_direction                   :   OUT   std_logic  -- ufix1
        );
END pwm_controller_pwm_controller_pcore_addr_decoder;


ARCHITECTURE rtl OF pwm_controller_pwm_controller_pcore_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL const_z                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_axi_enable            : std_logic;  -- ufix1
  SIGNAL reg_enb_axi_enable               : std_logic;  -- ufix1
  SIGNAL write_reg_axi_enable             : std_logic;  -- ufix1
  SIGNAL data_in_enable                   : std_logic;  -- ufix1
  SIGNAL decode_sel_enable                : std_logic;  -- ufix1
  SIGNAL reg_enb_enable                   : std_logic;  -- ufix1
  SIGNAL write_reg_enable                 : std_logic;  -- ufix1
  SIGNAL data_in_duty                     : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL decode_sel_duty                  : std_logic;  -- ufix1
  SIGNAL reg_enb_duty                     : std_logic;  -- ufix1
  SIGNAL write_reg_duty                   : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_in_direction                : std_logic;  -- ufix1
  SIGNAL decode_sel_direction             : std_logic;  -- ufix1
  SIGNAL reg_enb_direction                : std_logic;  -- ufix1
  SIGNAL write_reg_direction              : std_logic;  -- ufix1

BEGIN
  const_z <= (OTHERS => 'Z');


  data_read <= std_logic_vector(const_z);

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  const_1 <= '1';

  enb <= const_1;

  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_axi_enable <= '1' WHEN addr_sel_unsigned = 1 ELSE
      '0';

  reg_enb_axi_enable <= decode_sel_axi_enable AND wr_enb;

  reg_axi_enable_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      write_reg_axi_enable <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable = '1' THEN
        write_reg_axi_enable <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_process;


  write_axi_enable <= write_reg_axi_enable;

  data_in_enable <= data_write_unsigned(0);

  
  decode_sel_enable <= '1' WHEN addr_sel_unsigned = 64 ELSE
      '0';

  reg_enb_enable <= decode_sel_enable AND wr_enb;

  reg_enable_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      write_reg_enable <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_enable = '1' THEN
        write_reg_enable <= data_in_enable;
      END IF;
    END IF;
  END PROCESS reg_enable_process;


  write_enable <= write_reg_enable;

  data_in_duty <= data_write_unsigned(7 DOWNTO 0);

  
  decode_sel_duty <= '1' WHEN addr_sel_unsigned = 65 ELSE
      '0';

  reg_enb_duty <= decode_sel_duty AND wr_enb;

  reg_duty_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      write_reg_duty <= to_unsigned(2#00000000#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_duty = '1' THEN
        write_reg_duty <= data_in_duty;
      END IF;
    END IF;
  END PROCESS reg_duty_process;


  write_duty <= std_logic_vector(write_reg_duty);

  data_in_direction <= data_write_unsigned(0);

  
  decode_sel_direction <= '1' WHEN addr_sel_unsigned = 66 ELSE
      '0';

  reg_enb_direction <= decode_sel_direction AND wr_enb;

  reg_direction_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      write_reg_direction <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_direction = '1' THEN
        write_reg_direction <= data_in_direction;
      END IF;
    END IF;
  END PROCESS reg_direction_process;


  write_direction <= write_reg_direction;

END rtl;

