-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM_controller\PWM_Controller_pkg.vhd
-- Created: 2015-01-15 16:33:55
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE PWM_Controller_pkg IS
  TYPE T_state_type_is_Chart IS (IN_HIGH, IN_LOW, IN_S1, IN_S2);
END PWM_Controller_pkg;

