#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE ZedBoard
#define MW_CLOCKING_CPUCLOCKRATEMHZ 800
#define MW_RTOS 0
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_RUNTIME_BUILDACTION 1
#define MW_MULTI_TASKING_MODE 1
