-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PWM_controller\PWM_Controller_pkg.vhd
-- Created: 2014-10-15 17:50:17
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE PWM_Controller_pkg IS
  TYPE T_state_type_is_Chart IS (IN_HIGH, IN_LOW, IN_S1, IN_S2);
END PWM_Controller_pkg;

