# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/ipcore [current_fileset]

add_files C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/system_top.bd
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_clk_wiz_0_0/system_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_clk_wiz_0_0/system_top_clk_wiz_0_0_OOC.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_clk_wiz_0_0/system_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_proc_sys_reset_0_0/system_top_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_proc_sys_reset_0_0/system_top_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_proc_sys_reset_0_0/system_top_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_processing_system7_0_0/system_top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/ip/system_top_auto_pc_3/system_top_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/system_top_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/system_top.bd]

read_vhdl C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system_top/hdl/system_top_wrapper.vhd
read_xdc C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_constraint.xdc
set_property used_in_implementation false [get_files C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj/vivado_prj.data/wt [current_project]
set_property parent.project_dir C:/MATLAB/quadcopter/PWMController/hdl_prj/vivado_ip_prj [current_project]
synth_design -top system_top_wrapper -part xc7z020clg484-1
write_checkpoint system_top_wrapper.dcp
report_utilization -file system_top_wrapper_utilization_synth.rpt -pb system_top_wrapper_utilization_synth.pb
