#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__


#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE ZedBoard
#define MW_CLOCKING_CPUCLOCKRATEMHZ 800
#define MW_RTOS 0
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_RUNTIME_BUILDACTION 1
#define MW_EXTMODE_TRANSPORT TCP/IP
#define MW_EXTMODE_COMPORT 
#define MW_EXTMODE_BAUDRATE 
#define MW_EXTMODE_IPADDRESS '169.254.1.10'
#define MW_EXTMODE_PORT 17725
#define MW_EXTMODE_VERBOSE 0
#define MW_EXTMODE_MEXARGS 
#define MW_MULTI_TASKING_MODE 1

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif
