-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\PmodACL_IP_14a\pmodacl_ip_14a_hdl_dut_pcore_dut.vhd
-- Created: 2015-02-17 15:23:15
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pmodacl_ip_14a_hdl_dut_pcore_dut
-- Source Path: pmodacl_ip_14a_hdl_dut_pcore/pmodacl_ip_14a_hdl_dut_pcore_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pmodacl_ip_14a_hdl_dut_pcore_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        CMD                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        CMD_VLD                           :   IN    std_logic;  -- ufix1
        SDO                               :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        X                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        Y                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        Z                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        XYZ_Valid                         :   OUT   std_logic;  -- ufix1
        CS                                :   OUT   std_logic;  -- ufix1
        SCLK                              :   OUT   std_logic;  -- ufix1
        SDI                               :   OUT   std_logic  -- ufix1
        );
END pmodacl_ip_14a_hdl_dut_pcore_dut;


ARCHITECTURE rtl OF pmodacl_ip_14a_hdl_dut_pcore_dut IS

  -- Component Declarations
  COMPONENT hdl_dut
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          CMD                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          CMD_VLD                         :   IN    std_logic;  -- ufix1
          SDO                             :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          X                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Y                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Z                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          XYZ_Valid                       :   OUT   std_logic;  -- ufix1
          CS                              :   OUT   std_logic;  -- ufix1
          SCLK                            :   OUT   std_logic;  -- ufix1
          SDI                             :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hdl_dut
    USE ENTITY work.hdl_dut(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL CMD_VLD_sig                      : std_logic;  -- ufix1
  SIGNAL SDO_sig                          : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL X_sig                            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Y_sig                            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Z_sig                            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL XYZ_Valid_sig                    : std_logic;  -- ufix1
  SIGNAL CS_sig                           : std_logic;  -- ufix1
  SIGNAL SCLK_sig                         : std_logic;  -- ufix1
  SIGNAL SDI_sig                          : std_logic;  -- ufix1

BEGIN
  u_hdl_dut : hdl_dut
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              CMD => CMD,  -- ufix16
              CMD_VLD => CMD_VLD_sig,  -- ufix1
              SDO => SDO_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              X => X_sig,  -- ufix16
              Y => Y_sig,  -- ufix16
              Z => Z_sig,  -- ufix16
              XYZ_Valid => XYZ_Valid_sig,  -- ufix1
              CS => CS_sig,  -- ufix1
              SCLK => SCLK_sig,  -- ufix1
              SDI => SDI_sig  -- ufix1
              );

  CMD_VLD_sig <= CMD_VLD;

  SDO_sig <= SDO;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  X <= X_sig;

  Y <= Y_sig;

  Z <= Z_sig;

  XYZ_Valid <= XYZ_Valid_sig;

  CS <= CS_sig;

  SCLK <= SCLK_sig;

  SDI <= SDI_sig;

END rtl;

