-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\EncoderRead\dut_EncoderRead_pkg.vhd
-- Created: 2015-02-11 17:56:59
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE dut_EncoderRead_pkg IS
  TYPE T_state_type_is_Channel_A_Interrupt IS (IN_I1, IN_I2, IN_I3, IN_I4);
  TYPE T_state_type_is_Channel_B_Interrupt IS (IN_I1, IN_I2, IN_I3, IN_I4);
END dut_EncoderRead_pkg;

