%% Product Guide
% This page is generated by HDL Coder for IP core:
% PWM_controller_PWM_Controller_ipcore.
% 
% Please open the IP Core Generation Report using following link:
% 
% <file://PWM_controller_ip_core_report.html doc/PWM_controller_ip_core_report.html>
