-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZedBoardTest\zedboardtest_subsystem_pcore_dut.vhd
-- Created: 2015-02-12 14:24:02
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: zedboardtest_subsystem_pcore_dut
-- Source Path: zedboardtest_subsystem_pcore/zedboardtest_subsystem_pcore_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY zedboardtest_subsystem_pcore_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        In1                               :   IN    std_logic;  -- ufix1
        In2                               :   IN    std_logic;  -- ufix1
        In3                               :   IN    std_logic;  -- ufix1
        In4                               :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        Out1                              :   OUT   std_logic;  -- ufix1
        Out2                              :   OUT   std_logic;  -- ufix1
        Out3                              :   OUT   std_logic;  -- ufix1
        Out4                              :   OUT   std_logic  -- ufix1
        );
END zedboardtest_subsystem_pcore_dut;


ARCHITECTURE rtl OF zedboardtest_subsystem_pcore_dut IS

  -- Component Declarations
  COMPONENT Subsystem
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          In1                             :   IN    std_logic;  -- ufix1
          In2                             :   IN    std_logic;  -- ufix1
          In3                             :   IN    std_logic;  -- ufix1
          In4                             :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          Out1                            :   OUT   std_logic;  -- ufix1
          Out2                            :   OUT   std_logic;  -- ufix1
          Out3                            :   OUT   std_logic;  -- ufix1
          Out4                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_sig                          : std_logic;  -- ufix1
  SIGNAL In2_sig                          : std_logic;  -- ufix1
  SIGNAL In3_sig                          : std_logic;  -- ufix1
  SIGNAL In4_sig                          : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Out1_sig                         : std_logic;  -- ufix1
  SIGNAL Out2_sig                         : std_logic;  -- ufix1
  SIGNAL Out3_sig                         : std_logic;  -- ufix1
  SIGNAL Out4_sig                         : std_logic;  -- ufix1

BEGIN
  u_Subsystem : Subsystem
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              In1 => In1_sig,  -- ufix1
              In2 => In2_sig,  -- ufix1
              In3 => In3_sig,  -- ufix1
              In4 => In4_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              Out1 => Out1_sig,  -- ufix1
              Out2 => Out2_sig,  -- ufix1
              Out3 => Out3_sig,  -- ufix1
              Out4 => Out4_sig  -- ufix1
              );

  In1_sig <= In1;

  In2_sig <= In2;

  In3_sig <= In3;

  In4_sig <= In4;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  Out1 <= Out1_sig;

  Out2 <= Out2_sig;

  Out3 <= Out3_sig;

  Out4 <= Out4_sig;

END rtl;

